// app.js — UI only (data.js must be loaded first)
var h=React.createElement,us=React.useState,ue=React.useEffect,ur=React.useRef;
var Ft="'Open Sans',sans-serif";
var B={fontFamily:Ft,fontWeight:800},S={fontFamily:Ft,fontWeight:600},R={fontFamily:Ft,fontWeight:400},Lt={fontFamily:Ft,fontWeight:300};
var CC={green:"#86BC25",black:"#000",bg:"#0A0A0A",card:"#141414",border:"#222",g6:"#666",g4:"#999",g2:"#CCC",white:"#FFF",blue:"#0097A9",bh:"#00ADC2"};

function Logo(){return h("svg",{height:48,viewBox:"0 0 400 80",xmlns:"http://www.w3.org/2000/svg"},h("style",null,"@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap');"),h("text",{x:"0",y:"64",fill:"#FFF",style:{fontFamily:"'Open Sans',Impact,'Arial Black',sans-serif",fontWeight:800,fontSize:"76px",letterSpacing:"-2px"}},"Deloitte"),h("circle",{cx:"322",cy:"56",r:"10",fill:"#86BC25"}));}

function Crumb(p){return h("div",{style:{display:"flex",alignItems:"center",gap:8,padding:"12px 24px",borderBottom:"1px solid "+CC.border}},p.items.map(function(it,i){return h("div",{key:i,style:{display:"flex",alignItems:"center",gap:8}},i>0?h("span",{style:{color:CC.g6,fontSize:12}},"\u203A"):null,it.onClick?h("button",{onClick:it.onClick,style:Object.assign({color:CC.g4,fontSize:12,cursor:"pointer",background:"none",border:"none"},R)},it.label):h("span",{style:Object.assign({color:CC.white,fontSize:12},S)},it.label));}));}

function AnimSphere(p){var size=p.size||500,ref=ur(null),raf=ur(0);ue(function(){var cv=ref.current;if(!cv)return;var ctx=cv.getContext("2d"),dpr=window.devicePixelRatio||1;cv.width=size*dpr;cv.height=size*dpr;ctx.scale(dpr,dpr);var cx=size/2,cy=size/2,r=size*.4,t=0,run=true,i;var arcs=[],nds=[];for(i=0;i<90;i++)arcs.push({tl:(Math.random()-.3)*Math.PI*.8,ph:Math.random()*Math.PI*2,sp:.3+Math.random()*.6,ln:.15+Math.random()*.35,br:.4+Math.random()*.6});for(i=0;i<60;i++)nds.push({tl:(Math.random()-.3)*Math.PI*.8,ph:Math.random()*Math.PI*2,sp:.2+Math.random()*.5,sz:1+Math.random()*2.5});function pr(th,tl){var x=r*Math.cos(th),y=r*Math.sin(th)*Math.cos(tl),z=r*Math.sin(th)*Math.sin(tl);return{x:cx+x,y:cy-y,z:z};}function draw(){if(!run)return;ctx.clearRect(0,0,size,size);t+=.008;var g=ctx.createRadialGradient(cx,cy,r*.2,cx,cy,r*1.3);g.addColorStop(0,"rgba(134,188,37,.04)");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fillRect(0,0,size,size);for(i=0;i<arcs.length;i++){var a=arcs[i],s0=a.ph+t*a.sp,e0=s0+a.ln*Math.PI;ctx.beginPath();var st=false;for(var j=0;j<=30;j++){var th=s0+(e0-s0)*(j/30),pp=pr(th,a.tl),d=(pp.z+r)/(2*r);if(d<.15){st=false;continue;}ctx.strokeStyle="rgba(134,188,37,"+Math.max(0,a.br*(.1+d*.7)*(1-Math.abs(j/30-.5)*1.5))+")";ctx.lineWidth=.5+d*1.8;if(!st){ctx.moveTo(pp.x,pp.y);st=true;}else ctx.lineTo(pp.x,pp.y);}ctx.stroke();}for(i=0;i<nds.length;i++){var n=nds[i],th2=n.ph+t*n.sp,pp2=pr(th2,n.tl),d2=(pp2.z+r)/(2*r);if(d2<.2)continue;var a2=.2+d2*.8;ctx.beginPath();ctx.arc(pp2.x,pp2.y,n.sz+3,0,Math.PI*2);ctx.fillStyle="rgba(134,188,37,"+(a2*.2)+")";ctx.fill();ctx.beginPath();ctx.arc(pp2.x,pp2.y,n.sz*d2,0,Math.PI*2);ctx.fillStyle="rgba("+(120+d2*60)+","+(200+d2*50)+",30,"+a2+")";ctx.fill();}raf.current=requestAnimationFrame(draw);}draw();return function(){run=false;cancelAnimationFrame(raf.current);};},[]); return h("canvas",{ref:ref,style:{width:size,height:size}});}

function OrgSphere(p){var size=p.size||320,ref=ur(null),raf=ur(0);ue(function(){var cv=ref.current;if(!cv)return;var ctx=cv.getContext("2d"),dpr=window.devicePixelRatio||1;cv.width=size*dpr;cv.height=size*dpr;ctx.scale(dpr,dpr);var cx=size/2,cy=size/2,r=size*.36,t=0,run=true,i,j;var dots=[],ten=[],bumps=[];for(i=0;i<600;i++)dots.push({la:(Math.random()-.5)*Math.PI,lo:Math.random()*Math.PI*2,j:.92+Math.random()*.16,sz:.5+Math.random()*2,br:.3+Math.random()*.7});for(i=0;i<45;i++)ten.push({sla:-Math.PI*.3-Math.random()*Math.PI*.3,slo:Math.random()*Math.PI*2,cu:-.5-Math.random()*1.5,ln:.3+Math.random()*.6,sp:.1+Math.random()*.15,w:1+Math.random()*2,br:.4+Math.random()*.6});for(i=0;i<8;i++){var la2=(Math.random()-.3)*Math.PI*.7,lo2=Math.random()*Math.PI*2,bR=.15+Math.random()*.2;for(j=0;j<35;j++)bumps.push({la:la2+(Math.random()-.5)*bR,lo:lo2+(Math.random()-.5)*bR,el:1+Math.random()*.12,sz:.8+Math.random()*1.5,br:.5+Math.random()*.5});}function pr(la,lo,rd){var y=rd*Math.sin(la),rr=rd*Math.cos(la);return{x:cx+rr*Math.cos(lo),y:cy-y,z:rr*Math.sin(lo)};}function draw(){if(!run)return;ctx.clearRect(0,0,size,size);t+=.005;var g=ctx.createRadialGradient(cx,cy+r*.3,0,cx,cy+r*.3,r*1.5);g.addColorStop(0,"rgba(134,188,37,.06)");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fillRect(0,0,size,size);var rot=t*.3;for(i=0;i<dots.length;i++){var d=dots[i],pp=pr(d.la,d.lo+rot,r*d.j),dp=(pp.z+r)/(2*r);if(dp<.1)continue;ctx.beginPath();ctx.arc(pp.x,pp.y,d.sz*dp,0,Math.PI*2);ctx.fillStyle="rgba(134,188,37,"+(d.br*(.1+dp*.7))+")";ctx.fill();}for(i=0;i<bumps.length;i++){var b=bumps[i],pp2=pr(b.la,b.lo+rot,r*b.el),dp2=(pp2.z+r*b.el)/(2*r*b.el);if(dp2<.15)continue;var a=b.br*(.15+dp2*.75);ctx.beginPath();ctx.arc(pp2.x,pp2.y,b.sz*dp2+2,0,Math.PI*2);ctx.fillStyle="rgba(134,188,37,"+(a*.25)+")";ctx.fill();ctx.beginPath();ctx.arc(pp2.x,pp2.y,b.sz*dp2,0,Math.PI*2);ctx.fillStyle="rgba("+(100+dp2*80)+","+(200+dp2*55)+","+(20+dp2*20)+","+a+")";ctx.fill();}for(i=0;i<ten.length;i++){var tr=ten[i];ctx.beginPath();var st=false;for(j=0;j<=30;j++){var f=j/30,la=tr.sla+f*tr.ln*Math.PI,lo=tr.slo+rot+f*tr.cu,ext=1+f*f*.6,pp3=pr(la,lo,r*ext),dp3=(pp3.z+r*ext)/(2*r*ext);if(dp3<.05){st=false;continue;}ctx.strokeStyle="rgba(134,188,37,"+Math.max(0,tr.br*(.1+dp3*.5)*(1-f*.7))+")";ctx.lineWidth=tr.w*(1-f*.5)*dp3;if(!st){ctx.moveTo(pp3.x,pp3.y);st=true;}else ctx.lineTo(pp3.x,pp3.y);}ctx.stroke();}raf.current=requestAnimationFrame(draw);}draw();return function(){run=false;cancelAnimationFrame(raf.current);};},[]); return h("canvas",{ref:ref,style:{width:size,height:size}});}

function Btn(p){var pad=p.size==="lg"?"14px 40px":p.size==="sm"?"8px 20px":"12px 28px",fs=p.size==="lg"?16:p.size==="sm"?13:14;return h("button",{onClick:p.onClick,disabled:p.disabled,style:Object.assign({borderRadius:50,padding:pad,fontSize:fs,background:CC.blue,color:CC.white,border:"none",opacity:p.disabled?.3:1,cursor:p.disabled?"not-allowed":"pointer",transition:"all .2s"},S),onMouseEnter:function(ev){if(!p.disabled)ev.currentTarget.style.background=CC.bh;},onMouseLeave:function(ev){if(!p.disabled)ev.currentTarget.style.background=CC.blue;}},p.children);}

function SI(p){var st=p.stage,sz=p.size||100,gid="sg"+st+Math.random().toString(36).slice(2,5),c1=st===0?"#00D4AA":st===1?"#86BC25":"#00B8D4",c2=st===0?"#007C6A":st===1?"#4A8C00":"#0077A9",u="url(#"+gid+")",inner=[];if(st===0)inner=[h("circle",{key:1,cx:44,cy:44,r:16,stroke:u,strokeWidth:3}),h("line",{key:2,x1:56,y1:56,x2:70,y2:70,stroke:u,strokeWidth:4,strokeLinecap:"round"}),h("circle",{key:3,cx:40,cy:40,r:2,fill:u,opacity:.8}),h("line",{key:4,x1:40,y1:34,x2:40,y2:46,stroke:u,strokeWidth:1,opacity:.4}),h("line",{key:5,x1:34,y1:40,x2:46,y2:40,stroke:u,strokeWidth:1,opacity:.4})];if(st===1)inner=[h("line",{key:1,x1:50,y1:75,x2:50,y2:28,stroke:u,strokeWidth:3,strokeLinecap:"round"}),h("path",{key:2,d:"M40 38 L50 24 L60 38",stroke:u,strokeWidth:3,strokeLinecap:"round",strokeLinejoin:"round",fill:"none"}),h("path",{key:3,d:"M50 55 C38 52,30 44,32 36 C34 44,40 48,50 50",stroke:u,strokeWidth:2,fill:u,opacity:.3}),h("path",{key:4,d:"M50 45 C62 42,68 34,66 28 C64 36,58 40,50 42",stroke:u,strokeWidth:2,fill:u,opacity:.3}),h("path",{key:5,d:"M35 75 L65 75",stroke:u,strokeWidth:1.5,strokeLinecap:"round",opacity:.3})];if(st===2)inner=[h("path",{key:1,d:"M50 20 C44 28,42 40,42 52 L50 56 L58 52 C58 40,56 28,50 20Z",stroke:u,strokeWidth:2.5,fill:u,fillOpacity:.15,strokeLinejoin:"round"}),h("path",{key:2,d:"M42 48 L34 58 L42 54",stroke:u,strokeWidth:2,fill:u,fillOpacity:.2,strokeLinejoin:"round"}),h("path",{key:3,d:"M58 48 L66 58 L58 54",stroke:u,strokeWidth:2,fill:u,fillOpacity:.2,strokeLinejoin:"round"}),h("circle",{key:4,cx:50,cy:38,r:4,stroke:u,strokeWidth:1.5,fill:u,fillOpacity:.1}),h("path",{key:5,d:"M46 56 C46 62,48 70,50 76 C52 70,54 62,54 56",stroke:"#FF8C00",strokeWidth:1.5,opacity:.7}),h("path",{key:6,d:"M48 56 C48 60,49 66,50 70 C51 66,52 60,52 56",fill:"#FFD700",opacity:.5})];return h("svg",{width:sz,height:sz,viewBox:"0 0 100 100",fill:"none"},h("defs",null,h("linearGradient",{id:gid,x1:20,y1:10,x2:80,y2:90,gradientUnits:"userSpaceOnUse"},h("stop",{offset:"0%",stopColor:c1}),h("stop",{offset:"100%",stopColor:c2}))),h("circle",{cx:50,cy:50,r:46,stroke:u,strokeWidth:1.5,opacity:.3}),h("circle",{cx:50,cy:50,r:38,stroke:u,strokeWidth:.8,opacity:.15}),inner);}

function PIcon(p){var sz=p.size||52;return h("svg",{width:sz,height:sz,viewBox:"0 0 36 36",fill:"none"},h("defs",null,h("linearGradient",{id:"pig",x1:0,y1:0,x2:36,y2:36},h("stop",{offset:"0%",stopColor:CC.blue}),h("stop",{offset:"100%",stopColor:"#005F6B"}))),h("rect",{rx:10,width:36,height:36,fill:"url(#pig)",opacity:.15}),h("circle",{cx:18,cy:13,r:5,stroke:CC.blue,strokeWidth:1.8,fill:"none"}),h("path",{d:"M8 30 C8 23 12 20 18 20 C24 20 28 23 28 30",stroke:CC.blue,strokeWidth:1.8,fill:"none",strokeLinecap:"round"}));}

function PC(p){var pd=p.pd,stage=p.stage;return h("div",{style:{display:"flex",flexDirection:"column",gap:10}},Object.keys(pd).map(function(cat){var items=pd[cat][stage],isOB=cat==="Onboarding",empty=Array.isArray(items)&&items.length===0;return h("div",{key:cat},isOB?h("div",{style:Object.assign({marginBottom:4,marginLeft:168,fontSize:12,fontStyle:"italic",color:"#F59E0B"},S)},"\u26A0 New Experienced or Campus Hires ONLY"):null,h("div",{style:{display:"flex",gap:10,alignItems:"stretch"}},h("div",{style:{width:160,flexShrink:0,borderRadius:8,padding:12,display:"flex",alignItems:"center",background:CC.green+"10",border:"1px solid "+CC.green+"18"}},h("span",{style:Object.assign({fontSize:12,color:CC.green},B)},cat)),h("div",{style:{flex:1,borderRadius:8,padding:12,background:CC.card,border:"1px solid "+CC.border,opacity:(items===NA||empty)?.4:1}},(items===NA||empty)?h("span",{style:Object.assign({fontSize:12,fontStyle:"italic",color:CC.g6},R)},items===NA?"N/A":"Coming soon"):h("div",{style:{display:"flex",flexDirection:"column",gap:6}},items.map(function(t,i){return h("div",{key:i,style:{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}},h("div",{style:{width:10,height:10,borderRadius:5,flexShrink:0,background:t.c}}),t.link?h("a",{href:t.link,target:"_blank",rel:"noopener noreferrer",style:Object.assign({fontSize:12,color:CC.g2,textDecoration:"none",transition:"color .2s"},R),onMouseEnter:function(ev){ev.currentTarget.style.color=CC.blue;ev.currentTarget.style.textDecoration="underline";},onMouseLeave:function(ev){ev.currentTarget.style.color=CC.g2;ev.currentTarget.style.textDecoration="none";}},t.n+" \u2197"):h("span",{style:Object.assign({fontSize:12,color:CC.g2},R)},t.n),t.cat?h("span",{style:Object.assign({fontSize:9,padding:"2px 6px",borderRadius:4,background:t.c+"20",color:t.c},S)},t.cat):null);})))));}));}

function BB(p){return h("button",{onClick:p.onClick,style:Object.assign({display:"flex",alignItems:"center",gap:8,marginTop:32,borderRadius:50,color:CC.g4,padding:"8px 20px",border:"1px solid "+CC.border,fontSize:13,background:"none",transition:"all .2s"},S),onMouseEnter:function(ev){ev.currentTarget.style.borderColor=CC.blue;ev.currentTarget.style.color=CC.blue;},onMouseLeave:function(ev){ev.currentTarget.style.borderColor=CC.border;ev.currentTarget.style.color=CC.g4;}},"\u2190 "+(p.label||"Back"));}

function App(){
var _s=us("landing"),scr=_s[0],setScr=_s[1];var _r=us(null),region=_r[0],setRegion=_r[1];var _l=us(null),level=_l[0],setLevel=_l[1];var _f=us(null),sf=_f[0],setSf=_f[1];var _t=us(null),stage=_t[0],setStage=_t[1];var _d=us(true),fade=_d[0],setFade=_d[1];
function go(s,o){o=o||{};setFade(false);setTimeout(function(){setScr(s);if(o.region!==undefined)setRegion(o.region);if(o.level!==undefined)setLevel(o.level);if(o.sf!==undefined)setSf(o.sf);if(o.stage!==undefined)setStage(o.stage);setFade(true);},200);}
var title=sf&&level?getTitle(sf,level):"";
var prof=[{k:"Position Title",v:title||"\u2014"},{k:"Location",v:region||"US"},{k:"JF",v:"Engineering & Product"},{k:"SF",v:sf||"\u2014"}];
function gBC(){var items=[{label:"Home",onClick:function(){go("landing");}}];if(scr==="region")items.push({label:"Region"});else if(scr==="level"){items.push({label:"Region",onClick:function(){go("region");}});items.push({label:"Level ("+region+")"});}else if(scr==="subfam"){items.push({label:"Region",onClick:function(){go("region");}});items.push({label:"Level",onClick:function(){go("level");}});items.push({label:"Sub-Family ("+level+")"});}else if(scr==="career"){items.push({label:"Region",onClick:function(){go("region");}});items.push({label:"Level",onClick:function(){go("level");}});items.push({label:sf,onClick:function(){go("subfam");}});items.push({label:"Career Stage"});}else if(scr==="pathway"){items.push({label:"Region",onClick:function(){go("region");}});items.push({label:"Level",onClick:function(){go("level");}});items.push({label:sf,onClick:function(){go("subfam");}});items.push({label:"Career Stage",onClick:function(){go("career");}});items.push({label:STG[stage].label});}return items;}
var pg={minHeight:"100vh",display:"flex",flexDirection:"column",background:CC.black};

return h("div",{style:Object.assign({minHeight:"100vh",background:CC.bg},R)},h("div",{style:{transition:"opacity .3s",opacity:fade?1:0}},

scr==="landing"?h("div",{style:pg},h("div",{style:{padding:"24px 32px"}},h(Logo)),h("div",{style:{flex:1,display:"flex",alignItems:"center",padding:"0 64px",gap:16,flexWrap:"wrap"}},h("div",{style:{flex:1,maxWidth:500}},h("h1",{style:Object.assign({fontSize:48,color:CC.white,lineHeight:1.15,margin:"0 0 20px"},Lt)},"Welcome to the",h("br"),h("span",{style:Object.assign({color:CC.green},B)},"Engineering & Product"),h("br"),"Learning Pathways Portal"),h("p",{style:Object.assign({fontSize:16,marginBottom:32,lineHeight:1.7,color:CC.g4,maxWidth:460},R)},"Deep Dive to Your Growth & Development Journey."),h(Btn,{size:"lg",onClick:function(){go("region");}},"Get Started")),h("div",{style:{flex:1,display:"flex",justifyContent:"center"}},h(AnimSphere,{size:500}))),h("div",{style:Object.assign({padding:24,fontSize:12,color:CC.g4},R)},"\u00A9 2026 Deloitte Development LLC.")):null,

scr==="region"?h("div",{style:pg},h("div",{style:{padding:"24px 32px"}},h(Logo)),h(Crumb,{items:gBC()}),h("div",{style:{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"0 24px",textAlign:"center"}},h(OrgSphere,{size:320}),h("h2",{style:Object.assign({fontSize:30,marginTop:24,marginBottom:12,color:CC.white},Lt)},"Select Your ",h("span",{style:B},"Region")),h("p",{style:Object.assign({fontSize:14,fontStyle:"italic",marginBottom:40,color:CC.green},R)},"Choose your region to explore the learning pathway."),h("div",{style:{display:"flex",gap:20}},h(Btn,{size:"lg",onClick:function(){go("level",{region:"US"});}},"United States"),h(Btn,{size:"lg",onClick:function(){go("level",{region:"India"});}},"India")),h(BB,{onClick:function(){go("landing");}}))):null,

scr==="level"?h("div",{style:pg},h("div",{style:{padding:"24px 32px",display:"flex",alignItems:"center",justifyContent:"space-between"}},h(Logo),h("span",{style:Object.assign({fontSize:14,padding:"6px 16px",borderRadius:50,background:CC.blue+"20",color:CC.blue,border:"1px solid "+CC.blue+"40"},S)},region)),h(Crumb,{items:gBC()}),h("div",{style:{flex:1,display:"flex",alignItems:"center",justifyContent:"center",padding:"0 24px",gap:48,flexWrap:"wrap"}},h("div",{style:{display:"flex",flexDirection:"column",alignItems:"center"}},h("h2",{style:Object.assign({fontSize:30,marginBottom:8,color:CC.white},Lt)},"Select Your ",h("span",{style:B},"Level")),h("p",{style:Object.assign({fontSize:14,fontStyle:"italic",marginBottom:40,color:CC.green},R)},"Select your level."),h("div",{style:{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,maxWidth:520,width:"100%"}},LVS.map(function(lv){return h(Btn,{key:lv,onClick:function(){go("subfam",{level:lv});}},lv);})),h(BB,{onClick:function(){go("region");},label:"Back to region"})),h("div",null,h(OrgSphere,{size:260})))):null,

scr==="subfam"?h("div",{style:pg},h("div",{style:{padding:"24px 32px",display:"flex",alignItems:"center",justifyContent:"space-between"}},h(Logo),h("div",{style:{display:"flex",gap:8}},h("span",{style:Object.assign({fontSize:14,padding:"6px 16px",borderRadius:50,background:CC.blue+"20",color:CC.blue,border:"1px solid "+CC.blue+"40"},S)},region),h("span",{style:Object.assign({fontSize:14,padding:"6px 16px",borderRadius:50,background:CC.green+"20",color:CC.green,border:"1px solid "+CC.green+"40"},S)},level))),h(Crumb,{items:gBC()}),h("div",{style:{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"0 24px"}},h("h2",{style:Object.assign({fontSize:30,marginBottom:8,color:CC.white},Lt)},"Select Your ",h("span",{style:B},"Sub-Family")),h("p",{style:Object.assign({fontSize:14,fontStyle:"italic",marginBottom:40,color:CC.green},R)},"Choose your sub-family."),h("div",{style:{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,maxWidth:800,width:"100%"}},SFL.map(function(s){var titles=SF_DATA[s]&&SF_DATA[s][level],hasLv=!!titles,isSE=s==="Software Engineering"&&level==="L30-L35",avail=hasLv?titles.some(function(t){return t!=="N/A";}):true,soon=!isSE;return h("button",{key:s,onClick:function(){if(avail)go("career",{sf:s});},disabled:!avail,style:{borderRadius:12,padding:16,textAlign:"left",background:CC.card,border:"1px solid "+CC.border,opacity:avail?(soon?.55:1):.25,cursor:avail?"pointer":"not-allowed",transition:"all .2s"},onMouseEnter:function(ev){if(avail){ev.currentTarget.style.borderColor=CC.blue;ev.currentTarget.style.boxShadow="0 0 20px "+CC.blue+"20";}},onMouseLeave:function(ev){ev.currentTarget.style.borderColor=CC.border;ev.currentTarget.style.boxShadow="none";}},h("div",{style:Object.assign({fontSize:14,marginBottom:4,color:CC.white},S)},s),h("div",{style:Object.assign({fontSize:12,color:soon?"#F59E0B":CC.g4},R)},!avail?"Level not activated":soon?"Coming soon":titles.filter(function(t){return t!=="N/A";}).join(" / ")));})),h(BB,{onClick:function(){go("level");},label:"Back to levels"}))):null,

scr==="career"?h("div",{style:pg},h("div",{style:{padding:"24px 32px"}},h(Logo)),h(Crumb,{items:gBC()}),h("div",{style:{flex:1,display:"flex",flexDirection:"column",padding:"0 56px"}},h("div",{style:{display:"flex",flexWrap:"wrap",gap:"4px 32px",marginBottom:16,padding:"12px 16px",borderRadius:8,background:CC.card,border:"1px solid "+CC.border}},prof.map(function(p){return h("span",{key:p.k,style:Object.assign({fontSize:12},R)},h("span",{style:{color:CC.g4}},p.k+": "),h("span",{style:Object.assign({color:CC.green},S)},p.v));})),h("p",{style:Object.assign({fontSize:14,fontStyle:"italic",marginBottom:16,color:CC.green},R)},"Select a career stage."),h("div",{style:{flex:1,display:"flex",alignItems:"center",justifyContent:"center"}},h("div",{style:{position:"relative",width:"100%",maxWidth:900,height:400}},h("svg",{style:{position:"absolute",inset:0,width:"100%",height:"100%"},viewBox:"0 0 900 400",fill:"none",preserveAspectRatio:"none"},h("path",{d:"M0 360 C120 360,200 310,320 270 C440 230,500 170,620 130 C740 90,820 45,900 25",stroke:CC.green,strokeWidth:3,opacity:.35}),h("path",{d:"M0 360 C120 360,200 310,320 270 C440 230,500 170,620 130 C740 90,820 45,900 25 L900 400 L0 400 Z",fill:CC.green,opacity:.03})),[{left:"18%",bottom:"5%"},{left:"50%",bottom:"30%"},{left:"82%",bottom:"56%"}].map(function(pos,i){return h("div",{key:i,style:Object.assign({position:"absolute",transform:"translateX(-50%)",display:"flex",flexDirection:"column",alignItems:"center"},pos)},h("div",{style:{borderRadius:16,padding:20,display:"flex",flexDirection:"column",alignItems:"center",cursor:"pointer",background:CC.card+"E0",border:"1px solid "+CC.border,minWidth:170,transition:"all .2s"},onClick:function(){go("pathway",{stage:i});},onMouseEnter:function(ev){ev.currentTarget.style.borderColor=CC.blue;ev.currentTarget.style.boxShadow="0 0 28px "+CC.blue+"30";},onMouseLeave:function(ev){ev.currentTarget.style.borderColor=CC.border;ev.currentTarget.style.boxShadow="none";}},h(SI,{stage:i,size:95}),h("span",{style:Object.assign({fontSize:16,marginTop:8,color:CC.white},B)},STG[i].label),h("span",{style:Object.assign({fontSize:12,marginTop:4,marginBottom:12,color:CC.g4},R)},STG[i].period),h(Btn,{size:"sm",onClick:function(ev){ev.stopPropagation();go("pathway",{stage:i});}},STG[i].period)));}))),h(BB,{onClick:function(){go("subfam");},label:"Back to sub-family"}),h("div",{style:{height:24}}))):null,

scr==="pathway"?h("div",{style:pg},h("div",{style:{padding:"16px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid "+CC.border}},h(Logo),h("div",{style:{display:"flex",gap:8}},STG.map(function(s,i){return h("button",{key:i,onClick:function(){setStage(i);},style:Object.assign({borderRadius:50,fontSize:12,padding:"8px 16px",background:stage===i?CC.blue:"transparent",color:stage===i?CC.white:CC.blue,border:"1.5px solid "+(stage===i?CC.blue:CC.blue+"40"),transition:"all .2s"},S)},s.label+" \u2013 "+s.period);}))),h(Crumb,{items:gBC()}),h("div",{style:{flex:1,display:"flex",gap:20,padding:20}},h("div",{style:{width:192,flexShrink:0,borderRadius:12,padding:16,background:CC.card,border:"1px solid "+CC.border,display:"flex",flexDirection:"column"}},h("div",{style:{display:"flex",justifyContent:"center",marginBottom:12}},h(PIcon,{size:52})),prof.map(function(p){return h("div",{key:p.k,style:{marginBottom:8}},h("div",{style:Object.assign({color:CC.g6,fontSize:10,textTransform:"uppercase",letterSpacing:"0.5px"},S)},p.k),h("div",{style:Object.assign({color:CC.white,fontSize:12},S)},p.v));}),h("div",{style:{marginTop:12,paddingTop:12,borderTop:"1px solid "+CC.border,display:"flex",justifyContent:"center"}},h(SI,{stage:stage,size:72})),h("div",{style:Object.assign({textAlign:"center",marginTop:4,fontSize:10,color:CC.green},B)},STG[stage].label)),h("div",{style:{flex:1,minWidth:0}},h("div",{style:Object.assign({display:"inline-flex",alignItems:"center",gap:8,padding:"6px 16px",borderRadius:50,fontSize:12,marginBottom:16,background:CC.blue,color:CC.white},B)},h(SI,{stage:stage,size:18}),STG[stage].label+" \u2013 "+STG[stage].period),h(PC,{pd:getPD(sf,level,region),stage:stage}),h("div",{style:{marginTop:20,borderRadius:8,padding:10,display:"flex",flexWrap:"wrap",alignItems:"center",gap:12,background:CC.card,border:"1px solid "+CC.border}},h("span",{style:Object.assign({fontSize:12,color:CC.white},B)},"Learning Category:"),LCATS.map(function(lc){return h("div",{key:lc.label,style:{display:"flex",alignItems:"center",gap:6}},h("div",{style:{width:10,height:10,borderRadius:5,background:lc.color}}),h("span",{style:Object.assign({fontSize:12,color:CC.g4},R)},lc.label));})))),h("div",{style:{padding:"0 20px 20px"}},h("button",{onClick:function(){go("career");},style:Object.assign({fontSize:14,color:CC.g6,background:"none",border:"none",cursor:"pointer",transition:"color .2s"},S),onMouseEnter:function(ev){ev.currentTarget.style.color=CC.blue;},onMouseLeave:function(ev){ev.currentTarget.style.color=CC.g6;}},"\u2190 Back to career stages"))):null

));}

ReactDOM.render(h(App),document.getElementById("root"));
